Multi-crate project restructuration
jcorriveau23/backend-pool-nhl pull request #11
Opened 2023-07-02 00:47 UTC by TommyXR

Salut JF,

Comme on a jasé, voici le premier draft pour l'architecture qui je pense serait un bon compromis entre découplage et lisibilité.

L'app est divisée en 4 projets:

* `poolnhl_app` : contient seulement une fonction main qui démarre l'application et "colle" tous les modules ensemble.
* `poolnhl_routing`: Contient la logique au niveau de l'API (routing et conversion du modèle <-> output (JSON).
* `poolnhl_interface`: Contient les interfaces pour les différents services de l'application.
* `poolnhl_infrastructure`: contient l'implémentation des différents services et la logique de leur création.

Tiens moi au courant. Pour l'instant j'ai seulement fait le router de users pour qu'on puisse en discuter. Hésite pas à pull la branche et à regarder le repo localement.

2023-07-02 13:37 UTC, jcorriveau23 commented
Nice, je commence à comprendre, tu as découplé pas mal de chose. À première vu il manque ce appel 
![image](https://github.com/jcorriveau23/backend-pool-nhl/assets/60741764/903b48d0-0a36-4134-ade5-df97b0f03771)
qui prend une liste de users id et retoune les info de ces users. cet appel est utilisé par les pool pour avoir le nom des users. il manque aussi tout ce qui est dans jwt.rs relié  à la lecture du token sur chaque appel qui nécessite une authentification. Je pourrai m'occuper des autres service Pool/Auth et DailyLeaders en me basant sur ce que tu as fait. Tu avais en tête de fonctionner comment? On contribue sur le meme PR ?

2023-07-02 14:15 UTC, jcorriveau23 requested changes

2023-07-02 14:15 UTC, jcorriveau23 commented on crates/poolnhl_routing/src/endpoints/users_endpoints.rs
> +            .route("/users", get(UsersRouter::get_users))
Ce endpoint **/users** est meme pas utilisé, je pense qu'on pourrait le retirer, mais l'endpoint **user/:ids** était important. on passait une liste de user id et recevait les information de cette liste de user (surtout les nom qui était important. (Cela est nécessaire, puisque les pools stockent seulement les user id faisant partie du pool, et les user peuvent changer leur nom s'ils le désirent)

2023-07-02 14:15 UTC, jcorriveau23 commented on crates/poolnhl_routing/src/router.rs
> +        axum::Server::bind(&format!("127.0.0.1:{}", port).parse().unwrap())
Pas très important pour tout suite, mais je remarque qu'il n'y a pu de log sur les appels (qui indique le temps de process par exemple) et aussi quand on start l'app ca ne dit pas sur qu'elle port l'app a été démarré. Ce n'est pas important masi il faudra probablement ajouter ca (sur un autre PR peut etre).

2023-07-02 14:15 UTC, jcorriveau23 commented on crates/poolnhl_routing/Cargo.toml
> +axum = { version = "0.6.18", features = ["macros"] }
Plus une question, il y a tu un moyen avec les multi build de regroupper des dépendencies qui sont utilisé par plusieurs package genre tokio dans le Cargo.toml principale ?

2023-07-02 14:15 UTC, jcorriveau23 commented on crates/poolnhl_interface/src/users/model.rs
> +pub struct UserData {
Nice, on ne retourne plus le password :)! Je pense qu'il faut par exemple garder le ObjectID pour que lorsque les informations des users sont retourné le front end soit capable de mapper ObjectID du user -> info du user. (Relié à 2/3 autres commentaires)

2023-07-02 14:15 UTC, jcorriveau23 commented on crates/poolnhl_infrastructure/src/settings.rs
> +use std::fmt;
plus de lazy_statique! :)

2023-07-02 14:15 UTC, jcorriveau23 commented on crates/poolnhl_infrastructure/src/services/users_service.rs
> +            name: user.name,
Comme mentionné dans d'autres commentaires ici je pense qu'on voudra mapper le _id aussi à UserData. Dans le fond, la seule chose que je mapperais pas à UserData est le password.

2023-07-02 14:15 UTC, jcorriveau23 commented on crates/poolnhl_infrastructure/src/services/users_service.rs
> +        .map(|u| UserData {
Est ce néessaire de faire ca meme si tu implémente From<User> pour UserData?

2023-07-02 14:15 UTC, jcorriveau23 commented on crates/poolnhl_infrastructure/src/services/users_service.rs
> +    }
Relié à 2/3 autres commentaires, mais ca prendrait ici la fonction list_users(&self. ids: Vec<String>) qui retourne les info de la liste de user id. Le code avant: (le expect est quand meme dangereux il faut le faire autrement :P)
![image](https://github.com/jcorriveau23/backend-pool-nhl/assets/60741764/2367954a-fa4a-4d63-9eb1-373300dd183e)

2023-07-22 12:00 UTC, jcorriveau23 commented on crates/poolnhl_routing/src/endpoints/users_endpoints.rs
> +            .route("/users", get(UsersRouter::get_users))
done, retirer /users

2023-07-27 20:21 UTC, TommyXR commented on crates/poolnhl_infrastructure/src/services.rs
> +    pub secret: String,
Ceci devrait contenir seulement des services, pas besoin de garder ça là

2023-08-06 19:14 UTC, TommyXR commented on crates/poolnhl_routing/Cargo.toml
> +axum = { version = "0.6.18", features = ["macros"] }
Semble que oui, j'avais lu quelque chose du genre dans la doc de cargo. Mais y'a pas bcp de deps qui dont utilisées par toutes les crates

2023-08-10 14:08 UTC, TommyXR commented on crates/poolnhl_interface/src/pool/model.rs
> +pub const END_SEASON_DATE: &str = "2023-04-13";
Hm... ça va être à retravailer ça. Pas sûr qu'o nveut devoir recompiler pour pouvoir passer à une saison prochaine :D

2023-08-12 13:44 UTC, merged