implementation of Join/Leave socket room.
jcorriveau23/backend-pool-nhl pull request #12
Opened 2023-08-19 16:23 UTC by jcorriveau23

Salut Tommy premier PR pour le socket room, pour l'instant jai juste créer la structure et les commande join/leave room.

2023-08-23 02:41 UTC, TommyXR requested changes

2023-08-23 02:41 UTC, TommyXR commented on crates/poolnhl_infrastructure/src/services/draft_service.rs
> +        let draft_server_info = self.draft_server_info.lock().unwrap();
Préférer `.lock().expect("Could not acquire the mutex")`

2023-08-23 02:41 UTC, TommyXR commented on crates/poolnhl_infrastructure/src/services/draft_service.rs
> +            let mut draft_server_info = self.draft_server_info.lock().unwrap();
unwrap

2023-08-23 02:41 UTC, TommyXR commented on crates/poolnhl_interface/src/draft/model.rs
> +        // If the room does not exist create it.
Pas certain que ce soit une bonne idée

2023-08-23 02:41 UTC, TommyXR commented on crates/poolnhl_interface/src/draft/model.rs
> +        println!("user '{}' joining room '{}'\n", socket_id, pool_name);
println

2023-08-23 02:41 UTC, TommyXR commented on crates/poolnhl_interface/src/draft/model.rs
> +        }
`if let Some`

2023-08-23 02:41 UTC, TommyXR commented on crates/poolnhl_interface/src/draft/model.rs
> +        }
`if let Some`, ou probablement même mieux de `if let None` et early return

2023-08-23 02:41 UTC, TommyXR commented on crates/poolnhl_interface/src/draft/service.rs
> +    fn authentificate_web_socket(&self, token: &str, socket_addr: SocketAddr);
`autenticate`

2023-08-23 02:41 UTC, TommyXR commented on crates/poolnhl_routing/src/endpoints/draft_endpoints.rs
> +                println!("{}", command);
println

2023-08-23 02:41 UTC, TommyXR commented on crates/poolnhl_routing/src/endpoints/draft_endpoints.rs
> +    JoinRoom {
Probablement mieux

 ```rust
JoinRoom(String)
LeaveRoom(String)
etc
```


Aussi, tu devrais savoir dans quelle Room un user est. Il ne devrait pas y avoir de paramètre à la commande `LeaveRoom`

2023-08-23 02:41 UTC, TommyXR commented on crates/poolnhl_interface/src/draft/model.rs
> +#[derive(Debug)]
Je verrais plus quelque chose du genre


```rust
struct DraftServer {
    rooms: HashMap<String, Arc<Mutex<Room>>
}
```

Ça fait imo moyen de sens de garder un mutex sur le serveur au complet.

Aussi, les fonctions pour join/leave/etc devraient être dans l'implémentation de `Room`/`DraftServer` et non du service imo. On peut en parler bientôt si  tu veux.

2023-08-23 02:41 UTC, TommyXR commented on crates/poolnhl_interface/src/draft/model.rs
> +            .keys()
Nice. Bientôt on pourra faire ça en C++ aussi.

```cpp
mymap 
| views::keys 
| views::transform([](const auto& key) { return key.to_string(); }) 
| views::collect<std::vector>;
```

J'ai hâte

2023-08-23 02:41 UTC, TommyXR commented on crates/poolnhl_routing/src/endpoints/draft_endpoints.rs
> +        while let Some(Ok(msg)) = receiver.next().await {
Oublie pas de handle la déconnexion après le while loop, sinon si quelqu'un alt+f4 le LeaveRoom sera jamais envoyé et tout sera corrompu

2023-08-23 23:31 UTC, jcorriveau23 commented on crates/poolnhl_interface/src/draft/model.rs
> +#[derive(Debug)]
Il y a quelque chose que je comprend pas je pense. Dans l'exemple que tu donnes, si on prévoit ajouter des Room dans le HashMap, c'est le HashMap au complet qui doit etre mutable et donc le Mutex se doit d'être sur le HashMap ? 
Je vois ca comme ca:

struct DraftServer {
    rooms: Mutex<HashMap<String, Room>>
}

Aussi la clé de ton hash map tu voyais ca comme étant le nom du pool right ?

2023-08-23 23:35 UTC, jcorriveau23 commented on crates/poolnhl_routing/src/endpoints/draft_endpoints.rs
> +    JoinRoom {
En mettant le nom des champs comme ça, ça se sérialise mieux je pense, par exemple l'enum JoinRoom se sérialise comme suit en json:

`{"JoinRoom": {"pool_name": "pool-de-tommy"}}`  

Je sais pas trop comment ca se sérialiserait avec aucun nom de variable dans l'enum

2023-08-23 23:37 UTC, jcorriveau23 commented on crates/poolnhl_interface/src/draft/model.rs
> +        // If the room does not exist create it.
Je ne vois pas sur quoi ton commentaire pointe, est ce que c'est par rapport au fait que si la room n'existe pas, je la créé ?

2023-08-23 23:38 UTC, jcorriveau23 commented on crates/poolnhl_interface/src/draft/model.rs
> +            .keys()
Nice :)

2023-08-23 23:45 UTC, jcorriveau23 commented on crates/poolnhl_routing/src/endpoints/draft_endpoints.rs
> +        while let Some(Ok(msg)) = receiver.next().await {
totalement d'accord, pour ca je pense qu'il faut que j'ajoute le tokio::select!, je suis en train d'avancer ça.

2023-08-23 23:45 UTC, jcorriveau23 commented on crates/poolnhl_routing/src/endpoints/draft_endpoints.rs
> +                println!("{}", command);
à fixer assurément avant de closer le PR.

2023-08-23 23:45 UTC, jcorriveau23 commented on crates/poolnhl_interface/src/draft/model.rs
> +        println!("user '{}' joining room '{}'\n", socket_id, pool_name);
à fixer assurément avant de closer le PR.

2023-08-24 00:00 UTC, jcorriveau23 commented on crates/poolnhl_routing/src/endpoints/draft_endpoints.rs
> +    JoinRoom {
J'ai enlevé le parametre pool_name pour toutes les commandes sauf join room, je te laisse décider si ce commentaire est résolu.

2023-08-24 17:34 UTC, TommyXR commented on crates/poolnhl_interface/src/draft/model.rs
> +#[derive(Debug)]
C'est pas grave si c'est mutable, c'est justement la raison pour laquelle tu mets des shared pointers dans la map plutôt que la room direct. De cette façon tu passes le shared_ptr où tu en as besoin et même si la map change, les références aux rooms déjà existantes restent valides

2023-08-24 17:37 UTC, TommyXR commented on crates/poolnhl_interface/src/draft/model.rs
> +        // If the room does not exist create it.
Oups, j'ai mal highlight. Mais oui exact, créer une room si elle existe pas.

2023-09-08 23:36 UTC, merged